services:
  - type: web
    name: fraud-detection-api
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.main_mlflow:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: MODEL_SOURCE
        value: huggingface
      - key: HF_MODEL_REPO
        value: irfankarim/fraud-detection-lightgbm-v1
      - key: PORT
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://your-app.vercel.app
